### ISSUE TITLE
What happened to the Allen School?

### ISSUE THREAD

**Issue by BigBlueHat** [BuildMill/buildmill.github.io#3]
Back in December 2015 someone tore down a fabulous old school building--which, iirc, was "The Allen School" and had significant historical value (though apparently wasn't on the historic register...) in Greenville.

@agautsc know anything about this?

**Comment by agautsc** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/9822036-125161747_3-s4-v1.png?palette=1&width=246)

**Comment by BigBlueHat** [comment]
Now we know...
http://www.wyff4.com/news/historic-school-sacrificed-in-land-deal-for-townhomes-affordable-housing/38745696
![allen-school-2-jpg--1-](https://cloud.githubusercontent.com/assets/43209/14146255/f49e68f8-f664-11e5-90ab-aea942b5ed01.jpg)
